language: c

compiler:

  - gcc

before_install:

  - sudo apt-get update
  
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
  
install:

  - echo "Reached install section"
  
script:

  - echo "Reached Script Section"
  - gcc main.c -lm -o output
  - ./output  
